### ISSUE TITLE
NewtonsoftJson version update

### ISSUE THREAD

**Issue by nikembala** [RicoSuter/NJsonSchema#1006]
Hello,

Do you plan to update NewtonsoftJson dependency in the near future ?

Regards,
Nikolay Stamenov

**Comment by RicoSuter** [comment]
I try to keep it low so that it works with a lot of version. Is there a problem with that?

**Comment by nikembala** [comment]
I have the following situation, hope you can help.

I use T4 to generate code and inside the T4 I have:
```
<#@ assembly name="%userprofile%\.nuget\packages\njsonschema\10.0.10\lib\netstandard2.0\NJsonSchema.dll" #>
<#@ assembly name="%userprofile%\.nuget\packages\njsonschema.codegeneration\10.0.10\lib\netstandard2.0\NJsonSchema.CodeGeneration.dll" #>
<#@ assembly name="%userprofile%\.nuget\packages\njsonschema.codegeneration.csharp\10.0.10\lib\netstandard2.0\NJsonSchema.CodeGeneration.CSharp.dll" #>
<#@ assembly name="%userprofile%\.nuget\packages\Newtonsoft.Json\12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll" #>
```
followed by:
```
var schemaFromFile = JsonSchema.FromFileAsync("<input_file_path_here>");
NJsonSchema.JsonSchema nJsonSchema = schemaFromFile.Result;
var generator = new CSharpGenerator(nJsonSchema);
var file = generator.GenerateFile();
```
Here is part of the build output (I use target from MS to transform on build.
```
1>        C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\TextTemplating\Microsoft.TextTemplating.targets(340,5): error : Running transformation: System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
1>        C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\TextTemplating\Microsoft.TextTemplating.targets(340,5): error :    at NJsonSchema.JsonSchema.<FromJsonAsync>d__33.MoveNext()
1>        C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\TextTemplating\Microsoft.TextTemplating.targets(340,5): error :    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
1>        C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\TextTemplating\Microsoft.TextTemplating.targets(340,5): error :    at NJsonSchema.JsonSchema.FromJsonAsync(String data, String documentPath, Func`2 referenceResolverFactory)
1>        C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\TextTemplating\Microsoft.TextTemplating.targets(340,5): error :    at NJsonSchema.JsonSchema.<FromFileAsync>d__28.MoveNext()
1>        C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\TextTemplating\Microsoft.TextTemplating.targets(340,5): error : --- End of stack trace from previous location where exception was thrown ---
```
Also when I generate the file manually I get:
```
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.10.0 (Newtonsoft.Json v9.0.0.1) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
```
`[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.10.0 (Newtonsoft.Json v9.0.0.1)")]`

I assume that somewhere the version could not be updated to the latest.

Are you aware of some kind of workaround ?

**Comment by RicoSuter** [comment]
I think the main problem here is that T4 does not support binding redirects (?) and thus it is not recommended to use T4 anymore... can't you use the NSwag command line tools to do that?

**Comment by nikembala** [comment]
@RicoSuter thank you for the answer, will try to achieve it with NSwag.
