### ISSUE TITLE
Unable to cast byte enum to System.Int32

### ISSUE THREAD

**Issue by Ryan1729** [RicoSuter/NJsonSchema#1110]
I recently updated to version 12.x.x and now I'm getting an exception with the following error when I load the swagger page for my API.

```
System.InvalidCastException: Unable to cast object of type 'ApiViewModels.VerifiedStatus' to type 'System.Int32'.
   at NSwag.AspNetCore.Middlewares.SwaggerDocumentMiddleware.<GenerateSwaggerAsync>d__12.MoveNext()
```

Here's the definition for the `ApiViewModels.VerifiedStatus` type:
```c#
    public enum VerifiedStatus: byte
    {
        Unverified = 0,
        Verified = 1,
        Rejected = 0b1000_0000,
    }
```

If I make the enum an `int`, that is, change the definition to this:
```c#
    public enum VerifiedStatus //: byte
    {
        Unverified = 0,
        Verified = 1,
        Rejected = 0b1000_0000,
    }
```

then the exception goes away.

**Comment by RicoSuter** [comment]
Moved to NJS. Needs to be fixed here.

**Comment by brianfino** [comment]
Hello; I see this issue is still open -- is there anyone who could assist in resolving this item?  Schema generation still fails when there is an enum based on a Byte....  thank you!

**Comment by brianfino** [comment]
@RicoSuter your assistance would be much appreciated; this is a simple fix to [remove the cast](https://github.com/RicoSuter/NJsonSchema/blob/15c4367400521841b776b43c4540cd41cdfc4635/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L460)

All unit tests pass and will resolve the following exception: 
at NJsonSchema.Generation.JsonSchemaGenerator.ConvertDefaultValue(ContextualType type, Object defaultValue)
   at NSwag.Generation.AspNetCore.Processors.OperationParameterProcessor.CreatePrimitiveParameter(OperationProcessorContext context, ExtendedApiParameterDescription extendedApiParameter)
   at NSwag.Generation.AspNetCore.Processors.OperationParameterProcessor.Process(OperationProcessorContext operationProcessorContext)

**Comment by RicoSuter** [comment]
Can you create a PR in NJS?
