### ISSUE TITLE
Generating websocket hubs spec failed

### ISSUE THREAD

**Issue by lukapor** [RicoSuter/NJsonSchema#1465]
With new njsonschema. I supose that replacing library DotLiquid with Fluid broke this.

Here is stack trace
`Unhandled exception. System.InvalidOperationException: Error while rendering Liquid template TypeScript/Hub:
Fluid.ParseException: '{% endif %}' was expected at (11:1)
   at Fluid.FluidParserExtensions.Parse(FluidParser parser, String template)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.<Render>b__12_0(ValueTuple`2 _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
 ---> Fluid.ParseException: '{% endif %}' was expected at (11:1)
   at Fluid.FluidParserExtensions.Parse(FluidParser parser, String template)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.<Render>b__12_0(ValueTuple`2 _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   --- End of inner exception stack trace ---
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render()
   at LoopWebSocket.SpecsGenerator.SigSpec.CodeGeneration.TypeScript.SigSpecToTypeScriptGenerator.GenerateArtifacts(SigSpecDocument document) in C:\Nito\4O_Backend\src\apps\LoopWebSocket\SpecsGenerator\SigSpec.CodeGeneration.TypeScript\SigSpecToTypeScriptGenerator.cs:line 30
   at LoopWebSocket.SpecsGenerator.SigSpec.CodeGeneration.TypeScript.SigSpecToTypeScriptGenerator.GenerateFile(SigSpecDocument document) in C:\Nito\4O_Backend\src\apps\LoopWebSocket\SpecsGenerator\SigSpec.CodeGeneration.TypeScript\SigSpecToTypeScriptGenerator.cs:line 50
   at LoopWebSocket.Helpers.SpecsGenerator.WebSocketsSpecsGenerator.GenerateWebSocketsSpecsAsync(String destination) in C:\Nito\4O_Backend\src\apps\LoopWebSocket\Helpers\WebSocketsSpecsGenerator.cs:line 39`

I am using template Hub.liquid from SigSpec project.

**Comment by lahma** [comment]
Is it using `elseif` instead of correct `elsif`?

**Comment by RicoSuter** [comment]
We need to migrate SigSpec to Fluid as well, otherwise you cannot use latest NJsonSchema version with it.

**Comment by lukapor** [comment]
thx
