### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown

### ISSUE THREAD

**Issue by Gonkers** [RicoSuter/NJsonSchema#1466]
I have created a new .NET 6 console application and tried generating a schema using a large JSON file. (You can find an example here https://c2.scryfall.com/file/scryfall-bulk/all-cards/all-cards-20211216101126.json) Memory usage immediately spiked to almost 3GB and an out of memory exception was thrown.
## Error
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NJsonSchema.Infrastructure.DynamicApis.FileReadAllText(String filePath)
   at NJsonSchema.JsonSchema.<FromFileAsync>d__30.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NJsonSchema.JsonSchema.<FromFileAsync>d__29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Program.<<Main>$>d__0.MoveNext() in C:\NJsonSchemaExample\Program.cs:line 5

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
```
### Project File
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NJsonSchema" Version="10.6.6" />
  </ItemGroup>

</Project>
```
### Program.cs
```c#
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");

var jsonFilePath = @"C:\data\scryfall-all-cards-20211209221203.json";
var schema = await NJsonSchema.JsonSchema.FromFileAsync(jsonFilePath);

Console.WriteLine(schema);
```

**Comment by RicoSuter** [comment]
The file in the link is not a JSON Schema file but a JSON file. 
With enough memory you could load it but it won't work anyway as it cannot be serialized to a JSON Schema.

**Comment by Gonkers** [comment]
Okay I thought I could read JSON files to generate a Schema file from the structure of the data in it.  Second, no it doesn't matter the amount of ram that I have. I have 64GiB and it failed with OOM after allocating 2.8GiB. Thanks for reaching out anyway.

**Comment by lahma** [comment]
We fortunately fixes the OOM already, you will just get different error (invalid format) in the next release 😉

**Comment by Gonkers** [comment]
Great work. Thank you!
