### ISSUE TITLE
Cannot set SerializerOptions beause of bug in UpdateActualContractResolverAndSerializerSettings

### ISSUE THREAD

**Issue by watrakl** [RicoSuter/NJsonSchema#1551]
https://github.com/RicoSuter/NJsonSchema/blob/5476815d7f6e3172d6e384236135869a3bebeaea/src/NJsonSchema/Generation/JsonSchemaGeneratorSettings.cs#L258

When I try to change the the serializer settings from Newtonsoft to System.Text.Json by setting SerializerSettings to null and set new value for SerializerOptions there is an error "The setting SerializerSettings cannot be used when SerializerOptions is set.". It happens because in UpdateActualSerializerSettings when I set serializerSettings to null then new SerializerSettings object is created.

**Comment by simeyla** [comment]
I just had the same issue with the latest version.


> 6>System.InvalidOperationException: The setting SerializerSettings cannot be used when SerializerOptions is set.
> 6>   at NJsonSchema.Generation.JsonSchemaGeneratorSettings.UpdateActualContractResolverAndSerializerSettings()
> 6>   at NJsonSchema.Generation.JsonSchemaGeneratorSettings.set_SerializerSettings(JsonSerializerSettings value)
> 6>   at NSwag.Generation.OpenApiDocumentGeneratorSettings.ApplySettings(JsonSerializerSettings serializerSettings, Object mvcOptions) in /_/src/NSwag.Generation/OpenApiDocumentGeneratorSettings.cs:line 102
> 6>   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(Object serviceProvider) in /_/src/NSwag.Generation.AspNetCore/AspNetCoreOpenApiDocumentGenerator.cs:line 59

I was trying to follow the [instructions here](https://github.com/RicoSuter/NJsonSchema/wiki/JsonSchemaGenerator#systemtextjson-vs-newtonsoftjson).

I delved into the stack trace, and it looks like the intent is now to automatically get the Json settings from MvcOptions and you don't need to set them inside `AddOpenApiDocument()`

https://github.com/RicoSuter/NSwag/blob/92b168a7c10371e0d163c7fbd7900a590aa13c1e/src/NSwag.Generation.AspNetCore/AspNetCoreOpenApiDocumentGenerator.cs#L54

```
var mvcOptions = typedServiceProvider.GetRequiredService<IOptions<MvcOptions>>();
            var settings =
                mvcOptions.Value.OutputFormatters.Any(f => f.GetType().Name == "SystemTextJsonOutputFormatter") ?
                    GetSystemTextJsonSettings(typedServiceProvider) :
                    GetJsonSerializerSettings(typedServiceProvider) ?? GetSystemTextJsonSettings(typedServiceProvider);

            Settings.ApplySettings(settings, mvcOptions.Value);
```

So all you need to do is make sure you are using `services.AddMvc(...).AddJsonOptions(options => { ... })` and not `.AddNewtonsoftJson(...)`. Then the correct settings are automatically passed into `ApplySettings`.

@RicoSuter I think [this documentation is out of date?](https://github.com/RicoSuter/NJsonSchema/wiki/JsonSchemaGenerator#systemtextjson-vs-newtonsoftjson)

Note: You'd likely only run into this if you had two Startup.cs, one in an API project (that was set to AddNewtonsoftOptions and the other in your main project (converted to AddJsonOptions). That's what happened to me :-)
