### ISSUE TITLE
overridden "renamed" properties are not generated correctly

### ISSUE THREAD

**Issue by admir86** [RicoSuter/NJsonSchema#824]
If I override a property in a model class to define a new name for the DataMember, the property is generated twice. Once with "old" name, name like in the base class and once with the new name.

base class:
```C#
[DataContract]
public abstract class BaseViewModel<TKey>
{
	[DataMember]
	public virtual TKey Id { get; set; }

	[DataMember]
	public DateTime DateCreated { get; set; }

	[DataMember]
	public DateTime DateEdited { get; set; }
}
```

model:
```C#
[DataContract]
public class UserViewModel : BaseViewModel<long>
{
	[DataMember(Name = "userId")]
	public override long Id { set; get; }

	[DataMember]
	public string Firstname { get; set; }

	[DataMember]
	public string Lastname { get; set; }

	[DataMember]
	public string Email { get; set; }
}
```

if the option `flattenInheritanceHierarchy` is set to true, I would expect an output like the swagger has generated:
![image](https://user-images.githubusercontent.com/36576424/49178368-dff2d700-f34f-11e8-98fb-b87de06aca4d.png)

but the output looks like this:
```ts
export interface UserViewModel {
    id: number;
    dateCreated: Date;
    dateEdited: Date;
    userId: number;
    firstname?: string | undefined;
    lastname?: string | undefined;
    email?: string | undefined;
}
```

**Comment by RSuter** [comment]
Moved to NJS

**Comment by RSuter** [comment]
Test 

```
[DataContract]
public abstract class BaseViewModel<TKey>
{
    [DataMember]
    public virtual TKey Id { get; set; }

    [DataMember]
    public DateTime DateCreated { get; set; }

    [DataMember]
    public DateTime DateEdited { get; set; }
}

[DataContract]
public class UserViewModel : BaseViewModel<long>
{
    [DataMember(Name = "userId")]
    public override long Id { set; get; }

    [DataMember]
    public string Firstname { get; set; }

    [DataMember]
    public string Lastname { get; set; }

    [DataMember]
    public string Email { get; set; }
}

[Fact]
public async Task Abc()
{
    //// Arrange
    var settings = new JsonSchemaGeneratorSettings { FlattenInheritanceHierarchy = true };

    //// Act
    var schema = await JsonSchema4.FromTypeAsync<UserViewModel>(settings);
    var data = schema.ToJson();

    //// Assert
    Assert.False(schema.Properties.ContainsKey("Id"));
    Assert.True(schema.Properties.ContainsKey("userId"));
}
```

**Comment by admir86** [comment]
still same behavior...
should it be fixed in version 9.13.2 (nswag 12.0.5) ?

**Comment by RSuter** [comment]
I checked, its not that easy to fix. This is just the unit test to reproduce

**Comment by admir86** [comment]
OK, I thought the test should show that it's fixed :)

**Comment by admir86** [comment]
Hi  @RSuter 
nswag throws an error, if `BaseViewModel` is no more in the same project. I moved the base class in an other project, now I'm referencing the dll containing the base class.
(I'm using .net core 2.2)

nswag version:
```
NSwag NPM CLI
NSwag command line tool for .NET Core NetCore21, toolchain v12.0.7.0 (NJsonSchema v9.13.4.0 (Newtonsoft.Json v11.0.0.0))
```
```
System.InvalidOperationException: The JSON property 'id' is defined multiple times on type 'User.Models.UserViewModel'.
   at NJsonSchema.Generation.JsonSchemaGenerator.LoadPropertyOrFieldAsync(JsonProperty property, MemberInfo propertyInfo, Type parentType, JsonSchema4 parentSchema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GeneratePropertiesAsync(Type type, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateObjectAsync(Type type, JsonTypeDescription typeDescription, JsonSchema4 schema, JsonSchemaResolver schemaResolver) in C:\projects\nswag\src\NSwag.SwaggerGeneration\SwaggerJsonSchemaGenerator.cs:line 42
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateArray[TSchemaType](TSchemaType schema, Type type, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, TSchemaType schema, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, JsonSchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NSwag.SwaggerGeneration.SwaggerJsonSchemaGenerator.GenerateWithReferenceAndNullabilityAsync[TSchemaType](Type type, IEnumerable`1 parentAttributes, Boolean isNullable, JsonSchemaResolver schemaResolver, Func`3 transformation)
   at NSwag.SwaggerGeneration.Processors.OperationResponseProcessorBase.ProcessOperationDescriptionsAsync(IEnumerable`1 operationDescriptions, ParameterInfo returnParameter, OperationProcessorContext context, String successResponseDescription) in C:\projects\nswag\src\NSwag.SwaggerGeneration\Processors\OperationResponseProcessorBase.cs:line 136
   at NSwag.SwaggerGeneration.Processors.OperationResponseProcessorBase.ProcessResponseTypeAttributes(OperationProcessorContext operationProcessorContext, ParameterInfo returnParameter, IEnumerable`1 responseTypeAttributes) in C:\projects\nswag\src\NSwag.SwaggerGeneration\Processors\OperationResponseProcessorBase.cs:line 49
   at NSwag.SwaggerGeneration.WebApi.Processors.OperationResponseProcessor.ProcessAsync(OperationProcessorContext context) in C:\projects\nswag\src\NSwag.SwaggerGeneration.WebApi\Processors\OperationResponseProcessor.cs:line 50
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.RunOperationProcessorsAsync(SwaggerDocument document, Type controllerType, MethodInfo methodInfo, SwaggerOperationDescription operationDescription, List`1 allOperations, SwaggerGenerator swaggerGenerator, SwaggerSchemaResolver schemaResolver) in C:\projects\nswag\src\NSwag.SwaggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 234
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.AddOperationDescriptionsToDocumentAsync(SwaggerDocument document, Type controllerType, List`1 operations, SwaggerGenerator swaggerGenerator, SwaggerSchemaResolver schemaResolver) in C:\projects\nswag\src\NSwag.SwaggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 204
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.GenerateForControllerAsync(SwaggerDocument document, Type controllerType, SwaggerGenerator swaggerGenerator, SwaggerSchemaResolver schemaResolver) in C:\projects\nswag\src\NSwag.SwaggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 192
   at NSwag.SwaggerGeneration.WebApi.WebApiToSwaggerGenerator.GenerateForControllersAsync(IEnumerable`1 controllerTypes) in C:\projects\nswag\src\NSwag.SwaggerGeneration.WebApi\WebApiToSwaggerGenerator.cs:line 99
   at NSwag.Commands.SwaggerGeneration.WebApi.WebApiToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in C:\projects\nswag\src\NSwag.Commands\Commands\SwaggerGeneration\WebApi\WebApiToSwaggerCommand.cs:line 96
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader`1.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 70
   at NSwag.Commands.IsolatedCommandBase`1.<>c__DisplayClass17_0.<RunIsolatedAsync>b__0() in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedCommandBase.cs:line 60
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile)
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\IsolatedSwaggerOutputCommandBase.cs:line 47
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 268
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54child_process.js:644
    throw err;
    ^
```

**Comment by RSuter** [comment]
The main problem is that in swagger inheritance you cannot rename a property of a base schema - so what you tried to do here cannot be expressed in swagger... otherwise you could try to add the userId property with a custom schema processor - but then the base id would still be available...

**Comment by davifiamenghi** [comment]
I am getting the same error the same error overriding a property and set a RequiredAttribute , is it possible?

All classes have DataContract and DataMember

**Comment by RicoSuter** [comment]
> setting a RequiredAttribute, is it possible to achieve

This might in the spec if you just respecify the property in a concrete class. But this probably needs to be done manually in a schema processor
