### ISSUE TITLE
NJsonSchema Error while generating outputs

### ISSUE THREAD

**Issue by 19bartek92** [RicoSuter/NJsonSchema#892]
I get this error every try to generete outputs. It apears when "generate DTO types" is checked. What can be wrong? 
![obraz](https://user-images.githubusercontent.com/5702015/52096935-07248980-25c9-11e9-911d-1b27df07d9a4.png)

System.ArgumentException: The baseTypeName cannot equal typeName.
Parameter name: typeName

Runtime: NetCore22
   at NJsonSchema.CodeGeneration.CodeArtifact..ctor(String typeName, String baseTypeName, CodeArtifactType type, CodeArtifactLanguage language, ITemplate template)
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateClass(JsonSchema4 schema, String typeName)
   at NJsonSchema.CodeGeneration.GeneratorBase.GenerateTypes()
   at NJsonSchema.CodeGeneration.CSharp.CSharpGenerator.GenerateTypes()
   at NSwag.CodeGeneration.CSharp.Models.CSharpFileTemplateModel.GenerateDtoTypes() in C:\projects\nswag\src\NSwag.CodeGeneration.CSharp\Models\CSharpFileTemplateModel.cs:line 151
   at NSwag.CodeGeneration.CSharp.SwaggerToCSharpGeneratorBase.GenerateFile(String clientCode, IEnumerable`1 clientClasses, ClientGeneratorOutputType outputType) in C:\projects\nswag\src\NSwag.CodeGeneration.CSharp\SwaggerToCSharpGeneratorBase.cs:line 41
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(SwaggerDocument document, ClientGeneratorOutputType type) in C:\projects\nswag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 103
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<RunAsync>b__86_0() in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\SwaggerToCSharpClientCommand.cs:line 239
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.RunAsync() in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\SwaggerToCSharpClientCommand.cs:line 225
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\SwaggerToCSharpClientCommand.cs:line 217
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 77
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 31
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54

**Comment by RSuter** [comment]
It seems that there is an inheritance with the same type, e.g. Apple inherits from Apple (cycle). Can you provide a sample spec?

**Comment by human-unidentified** [comment]
> It seems that there is an inheritance with the same type, e.g. Apple inherits from Apple (cycle). Can you provide a sample spec?

Hi, 
I encountered the same error
System.ArgumentException: The baseTypeName 'EventAbstract' cannot equal typeName. (Parameter 'typeName')

Attached example spec. 
In swagger editor (https://editor.swagger.io/) spec opened successfully 
[swagger.zip](https://github.com/RicoSuter/NJsonSchema/files/9222989/swagger.zip)

**Comment by andreas-soroko** [comment]
Same here.
Looks like he struggles with this constellation. (generate with nswag)

<img width="562" alt="image" src="https://user-images.githubusercontent.com/47380084/190240470-55f46785-8b20-4f99-a704-64d8c7c0d720.png">


example app [Example.zip](https://github.com/RicoSuter/NJsonSchema/files/9569158/Example.zip)

@RicoSuter do you have an estimation when you have a chance to look into this?

**Comment by gil-ghalad** [comment]
Any progress in this topic? I am facing the same problem with the spec like this:
`{
  "openapi": "3.1.0",
  "info": {
    "title": "XXX",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "/api"
    }
  ],
  "paths": {
    
  },
  "components": {
    "schemas": {
      "Folder": {
        "required": [
          "$type",
          "items"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/Item"
          }
        ],
        "properties": {
          "$type": {
            "type": "string"
          },
          "items": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "$ref": "#/components/schemas/ItemBase"
                },
                {
                  "$ref": "#/components/schemas/Folder"
                },
                {
                  "$ref": "#/components/schemas/Item"
                },
                {
                  "$ref": "#/components/schemas/Item"
                },
                {
                  "$ref": "#/components/schemas/Folder"
                }
              ],
              "discriminator": {
                "propertyName": "$type",
                "mapping": {
                  "item": "#/components/schemas/Item",
                  "folder": "#/components/schemas/Folder"
                }
              }
            }
          }
        },
        "additionalProperties": false,
        "discriminator": {
          "propertyName": "$type",
          "mapping": {
            "folder": "#/components/schemas/Folder"
          }
        }
      },
      "Item": {
        "required": [
          "$type",
          "name"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ItemBase"
          }
        ],
        "properties": {
          "$type": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "id": {
            "type": "string",
            "nullable": true
          },
          "include": {
            "type": "boolean",
            "nullable": true
          },
          "compareStatus": {
            "$ref": "#/components/schemas/CompareStatus"
          }
        },
        "additionalProperties": false,
        "discriminator": {
          "propertyName": "$type",
          "mapping": {
            "item": "#/components/schemas/Item",
            "folder": "#/components/schemas/Folder"
          }
        }
      },
      "ItemBase": {
        "required": [
          "$type"
        ],
        "type": "object",
        "oneOf": [
          {
            "$ref": "#/components/schemas/Item"
          },
          {
            "$ref": "#/components/schemas/Folder"
          }
        ],
        "additionalProperties": false,
        "discriminator": {
          "propertyName": "$type",
          "mapping": {
            "item": "#/components/schemas/Item",
            "folder": "#/components/schemas/Folder"
          }
        }
      },
    }
  }
}`

The OpenApi json is created from .Net code that has such a declaration:
`[JsonPolymorphic(TypeDiscriminatorPropertyName = "_t")]
[JsonDerivedType(typeof(Item), "item")]
[JsonDerivedType(typeof(Folder), "folder")]
public class ItemBase;`

In my opinion, the above causes the problem. Maybe there is a way to set some option to enable generating code from the spec above, or to generate the spec in a way that it could be parsed and used to generate the code by NSwag. Can anyone help?
