### ISSUE TITLE
JsonSchemaFlatten + Swagger2tsclient = Error

### ISSUE THREAD

**Issue by abbotware** [RicoSuter/NJsonSchema#897]
the **swagger.json** is generated fine, but when that output is used for typescript generation it fails with the following:

```
5>System.InvalidOperationException: The properties 'name' are defined multiple times.
5>   at NJsonSchema.JsonSchema4.get_ActualProperties()
5>   at NJsonSchema.JsonSchema4.get_IsDictionary()
5>   at NJsonSchema.CodeGeneration.TypeScript.TypeScriptTypeResolver.IsDefinitionTypeSchema(JsonSchema4 schema)
5>   at NJsonSchema.CodeGeneration.TypeResolverBase.RegisterSchemaDefinitions(IDictionary`2 definitions)
5>   at NSwag.CodeGeneration.TypeScript.SwaggerToTypeScriptClientGenerator..ctor(SwaggerDocument document, SwaggerToTypeScriptClientGeneratorSettings settings, TypeScriptTypeResolver resolver) in C:\projects\nswag\src\NSwag.CodeGeneration.TypeScript\SwaggerToTypeScriptClientGenerator.cs:line 46
5>   at NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.<RunAsync>b__135_0() in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\SwaggerToTypeScriptClientCommand.cs:line 350
5>   at NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.RunAsync() in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\SwaggerToTypeScriptClientCommand.cs:line 343
5>   at NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\SwaggerToTypeScriptClientCommand.cs:line 336
5>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
5>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
5>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
5>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54
```

as soon as I remove JsonSchemaFlatten, the typescript is generated fine

and while I did report #896 - I have removed all DataContract / DataMemeber attributes from my class hierarchies

**Comment by abbotware** [comment]
this seems to be resovled
